# Site settings
title: Danielle C. Robinson, PhD
header-img: img/home-bg.jpg
email: daniellecrobinson@gmail.com
copyright_name: Danielle C. Robinson, PhD
description: "Danielle C. Robinson, PhD"
baseurl: ""
url: "http://daniellecrobinson.com/"
twitter_username: daniellecrobins
github_username:  daniellecrobinson
email_username:  daniellecrobinson@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 1
exclude: ["dat.json","README.md"]
